variable "backendkey" {}
variable "ipaddress" {}
variable "vpcname1" {}
variable "subipaddress" {}
variable "zones" {}
variable "subname1" {}
variable "igwname" {}
variable "drtname" {}
variable "sgname1" {}
variable "bucketnamee1" {}
variable "ami1" {}
variable "key" {}
variable "ec21name" {}
variable "ami2" {}
variable "key1" {}
variable "ec22name" {}
variable "type1" {}
variable "type2" {}
variable "targetname" {}
variable "i" {}
variable "pa" {}
variable "pro" {}
variable "appname" {}
variable "appvalue" {}
variable "apptype" {}
variable "protocal" {}
variable "targetname1" {}
variable "pat" {}
variable "prot" {}
variable "vall" {}
